//
//  GlobalVariable.swift
//  GetItWrite
//
//  Created by Hannah Billingsley-Dadd on 01/04/2022.
//

import Foundation
import SwiftUI

struct GlobalVariables {
	static var genres = ["Young Adult", "Adult", "Middle Grade", "Fantasy", "Magical Realism", "Histroical", "Romance", "Science Fiction", "Memoir", "Women's Fiction", "Short Stories", "Dystopian", "Mystery", "Thriller"]

	static var typeOfProject = ["Query Letter", "Short Story", "Chapter by Chapter MS Swap", "Query Package", "Synopsis"]

	static var profileColours = [Color("Grey"), Color("DarkBlue"), Color("DarkestGreen"), Color("DarkGreen"), Color("DarkYellow"), Color("LightBlue"), Color("LightGreen"), Color("Yellow")]
    
    static var inspiringQuotes = ["Let's go!", "The first draft just needs to be written.", "You've got this.", "Write now, edit later.", "Keep going!", "I believe in you.", "I can't wait to read your book.", "I can see the book's cover already.", "Believe in yourself as much as I believe in you.", "Keep writing!", "Writing isn't a hobby, it's way of life.", "Oof, I feel sorry for your characters in this one.", "Let's get this thing bookstore ready.", "Do I dare say best seller?", "Give your readers all the feels.", "Write, write, write!", "The best books all start with a blank page.", "Your name will look so good in print.", "You can thank me in the acknowledgements ;)", "How pretty will your books cover look when it's done?", "Anyone else feeling in a writing mood?", "Oof, our MC is gonna feel that one in the morning.", "Think our MCs life has been a bit too easy lately...", "Kiss already!", "I love it when a plan comes together.", "I wonder if you'll have a separate author social media account...", "Your name was made to go on a book cover.", "Can't wait to see this in a bookstore!", "You write it, I'll hype you up", "Write the book already!", "Write the words already!", "Watch that sweet sweet word count ticking up.", "You are blowing me away with this scene.", "Oh gosh. Goosebumps. Keep writing.", "Our poor poor MC.", "This might be my favourite scene yet.", "Your writing is on point today.", "Is it me or do we have a soon to be published author in the house?", "Just wait till your friends read your book.", "I assume I'm getting an invite to the book launch.", "So how will we punish our MC today...", "Imagine that feeling when you write the words the end.", "You are on fire today.", "Keep focused pal, we gotta get this thing finished.", "I don't wanna see any more distractions out of you.", "You do the writing and I just sit here. That's the game.", "So do you like always write this slowly or is it just today?", "Finish the chapter!", "Go on. You and I both know you're gonna finish this thing.", "Bring that Pinterest board to life.", "So what will your author signature be like?", "Let's finish this thing.", "The way you write like that? Takes my breath away.", "Gosh, you're talented.", "If you want to mention me in the dedication that would be cool. Just saying.", "You have got to finish this thing. It is so good.", "You might just be my favourite writer.", "One day you're gonna meet all your readers.", "You are so sexy when you write."]
    
    static var writingPrompts = [
      "Write about a character who wakes up with no reflection.",
      "Describe a city where everyone forgets everything at midnight.",
      "Write a story from the perspective of a tree in a busy park.",
      "A letter arrives 10 years late — and changes everything.",
      "Your main character can hear lies — but only from animals.",
      "The sun doesn't rise one morning. No one knows why.",
      "Write a breakup letter between a writer and their muse.",
      "A librarian discovers a book that predicts the future.",
      "Describe the last 60 seconds before a secret is revealed.",
      "Your character can pause time, but only for 3 minutes per day.",
      "Write about a world where people trade dreams as currency.",
      "Your character’s shadow starts acting independently.",
      "An AI gains sentience and immediately wants to write poetry.",
      "A ghost is haunting your character — to help them finish their novel.",
      "Write a dialogue between two exes trapped in an elevator.",
      "A magician's last trick accidentally opens a portal.",
      "Describe a ritual performed once every hundred years.",
      "Your character wakes up in someone else’s memory.",
      "An artist discovers their paintings come true.",
      "Every decision today is being controlled by a coin flip.",
      "Write a scene where no one can lie — even by omission.",
      "A ship is lost at sea, but the ocean speaks to one passenger.",
      "Write a fairytale set in a cyberpunk dystopia.",
      "Describe a meal that saves someone’s life.",
      "Two strangers discover they share the same recurring dream.",
      "A haunted house demands a story in exchange for safe passage.",
      "Your protagonist finds a notebook labeled ‘DO NOT WRITE HERE.’",
      "A planet where the seasons change every day.",
      "Write about the invention of an emotion.",
      "A love story that starts with a mistaken identity at a funeral.",
      "Your character wakes up in a world run by children.",
      "Every mirror shows a different version of the person looking in.",
      "Write about someone who remembers every version of reality.",
      "A dragon’s hoard contains only books.",
      "A town where people age backward.",
      "A love letter accidentally mailed to the wrong person.",
      "Describe a character who’s allergic to the future.",
      "Write a scene using only dialogue.",
      "A detective solves crimes by dreaming about them.",
      "A wedding is interrupted by a character from a forgotten story.",
      "Your character inherits a lighthouse and a cryptic diary.",
      "Write about a forgotten god returning for one last favor.",
      "Your character finds a map tattooed on their skin.",
      "Describe the end of a world — and the beginning of another.",
      "A spell goes wrong and swaps two characters’ writing styles.",
      "Write a monologue from a villain just before they change sides.",
      "A time traveler gets stuck in their least favorite era.",
      "Two rival authors are forced to co-write a bestseller.",
      "A character is cursed to speak only in song lyrics.",
      "Describe an underground library known only to a few.",
      "Your character discovers their imaginary friend is real — and angry.",
      "Write a scene where two characters argue using only metaphors.",
      "A world where dreams are taxed.",
      "Someone receives postcards from a place that doesn’t exist.",
      "A pandemic that only affects emotions.",
      "A bookstore that appears only at midnight.",
      "Your protagonist learns their story was written by someone else.",
      "A spaceship powered by stories.",
      "A machine that records your final thoughts before death.",
      "A child finds a key that unlocks a voice in their head.",
      "Write a scene involving a secret kept for generations.",
      "A message is found hidden in a famous painting.",
      "Your main character starts forgetting nouns — then names — then themselves.",
      "Describe a conversation between a human and a machine about art.",
      "Write a story that starts with a confession.",
      "A mirror that shows who you could have been.",
      "Two lovers communicate only through graffiti in the city.",
      "A stranger offers to erase one memory — but only one.",
      "A world where written words can be weaponized.",
      "Write about the moment the moon falls from the sky.",
      "A reality show where the prize is rewriting your past.",
      "Your character receives a letter from their future self — warning them.",
      "An archaeologist finds proof of a civilization that never existed.",
      "A new color is discovered, and it drives people mad.",
      "A town where everyone has the same recurring dream — until one night.",
      "Write from the POV of a character lost in a photograph.",
      "Your character discovers a hidden room in their house — with someone in it.",
      "Describe a society where people choose their own names at age 30.",
      "A fortune teller delivers a prophecy that was meant for someone else.",
      "A door appears in your character’s living room. No one else sees it.",
      "Write a comedy set during the apocalypse.",
      "A pen that writes only the truth — no matter what.",
      "Your character is interviewed by a historian from the future.",
      "Describe a party where time moves differently in each room.",
      "A character falls in love with someone from a different timeline.",
      "A world where birthdays determine your fate — literally.",
      "A creature who lives in unfinished stories.",
      "A museum that collects regrets.",
      "Write about someone who steals people’s voices — and sells them.",
      "Your protagonist must teach a class of mythical creatures.",
      "A train that stops only for people with broken hearts.",
      "Your character hears a song no one else can — and it’s getting louder.",
      "A courtroom where characters from different genres are on trial.",
      "Write about a holiday that doesn’t exist — but should.",
      "Describe a character whose lies become reality.",
      "An annual event where people relive one moment of their life.",
      "A library that lets you borrow moments from others’ lives.",
      "Your protagonist must write a story — or vanish.",
      "Write a horror story without using any supernatural elements.",
      "A spaceship crash-lands on Earth — with a familiar face aboard.",
      "A child who remembers their past five lives.",
      "Two people share a soul — and have never met.",
      "A famous author disappears mid-book — and you’re chosen to finish it.",
      "Describe a scene where the world ends quietly.",
      "A machine that prints your destiny, but it’s jammed.",
      "Your character learns they are the villain in someone else’s story.",
      "Write about a secret society of writers who shape reality.",
      "A child writes a story that starts coming true.",
      "A library where books are alive — and arguing.",
      "The stars in the sky begin to rearrange themselves. One message at a time."
    ];

}
