//
//  TsAndCsView.swift
//  GetItWrite
//
//  Created by Hannah Billingsley-Dadd on 01/07/2022.
//

import SwiftUI

struct TsAndCsView: View {
    var body: some View {
        NavigationView {
            ScrollView {
                Text("""
    Please read the following Terms of Service (these “Terms”) carefully before using the Get It Write (“GetItWrite”, “we,” “our,” or “us”) mobile application, available on the app store.
    
    GetItWrite provides a platform for writers to critique the work of others and receive critiques. The term "User" is any person or entity who views, uses, accesses, or browses any content on, and/or creates, uploads, posts, sends, receives or stores content. By accessing or using the app, each User agrees to these Terms. If any User does not agree to any portion of these Terms, that User should not access or otherwise use the mobile application.
    
    These Terms include important information about your legal rights, remedies, and obligations, including various limitations and exclusions, and provisions that govern the procedure, jurisdiction and venue of any disputes. By accessing or using the mobile application, you agree to be bound by these Terms and all additional terms incorporated by reference. If you do not agree to any portion of these Terms, you should not access or otherwise use the application.
    
    IV. General Terms
    This section contains terms applicable to all Users.
    
    4.1 Convenience and Information Only. Subject to these Terms, we hereby grant each User a non- transferable, non-exclusive, limited license to use and access the Mobile Application for your personal, non-commercial use. The Mobile Application is provided to you as a convenience and for your information only. By merely providing you access to and use of the Mobile Application, we do not warrant or represent that: (a) any statement, documents, images, graphics, logos, designs, audio, video, or any other information provided from or on the Mobile Application (collectively, the "Content") is accurate or complete; (b) the Content is up-to-date or current; (c) we have any obligation to update any Content; (d) the Content is free from technical inaccuracies or programming or typographical errors; (e) the Content is free from changes made by a third party; (f) your access to the Mobile Application will be free from interruptions, errors, computer viruses or other harmful components; and/or (g) any information obtained in response to comments or questions asked through the Mobile Application is or will be accurate or complete.
    
    4.2 Mobile Application Use and Content.
    
    (a) Use of the Mobile Application. The ownership of the Mobile Application, Content, and all rights therein are and will remain with GetItWrite. You may view, copy or print a single copy of any page from the Mobile Application for personal, non-commercial purposes if you do not remove, modify, or alter any copyright or proprietary rights notices that may be present. You may not otherwise use, modify, copy, print, display, distribute, publish, or sell any information, images or other Content from the Mobile Application without our express, prior, written consent. Any special rules for any software, downloads, and other items accessible through the Mobile Application may be included elsewhere in the Mobile Application and are incorporated into these Terms by reference.
    
    (b) Restrictions on Use. You may not: (i) remove or obscure any copyright, trademark, digital watermarks, proprietary legends or other proprietary notices from any portion of the Mobile Application; (ii) reproduce, modify, prepare derivative works based upon, distribute, license, lease, sell, resell, transfer, publicly display, publicly perform, transmit, stream, broadcast or otherwise exploit the Mobile Application, or any aspect of them, except as expressly permitted by us; (iii) decompile, reverse engineer, jeopardize the correct functioning of the Mobile Application, or disassemble the Mobile Application, or otherwise attempt to derive the source code of the software (including the tools, processes, methods, and infrastructure) that enables or underlies the Mobile Application, except as may be permitted by applicable law; (iv) cause or launch any programs, spiders, robots, or scripts or other automatic or manual devices or processes for the purpose of extracting, scraping, indexing, surveying, or otherwise data mining any portion of the Mobile Application, or unduly burdening or hindering the operation and/or functionality of any aspect of the Mobile Application; (v) attempt to gain unauthorized access to or impair any aspect of the Mobile Application, or the related systems, servers, or networks; (vi) use the Mobile Application to stalk, harass or harm another individual, or in any way that is in violation of any law or regulation; (vii) impersonate any person or entity, or otherwise misrepresent your affiliation with any person or entity; or (viii) use any portion of the Mobile Application or any Content in any manner that may give a false or misleading impression, attribution or statement as to us or any other person or entity.
    
    (c) Prohibited External Communication. Users are prohibited from soliciting or engaging the services or business of other Users or making, receiving or inviting payments for services by any means.
    4.3 Updates. We may make changes to the Mobile Application, the Content, the User Content (as defined below) or these Terms or stop providing any of the Mobile Application and/or the Content at any time and without further notice to you. We will make an effort to update the Mobile Application with any changes to these Terms, and you are encouraged to review these Terms frequently. Your continued access or use of the Mobile Application after such posting constitutes your consent to be bound by the Terms, as amended.
    
    4.4 Privacy and Electronic Communication. We know that privacy is very important to you, and it is very important to us as well. Personal data that you provide regarding yourself will be handled in accordance with our Privacy Policy located on the menu of the app.
    
    4.5 User Account, Password and Security. To the extent that you create a User account to access and use the Mobile Application ("User Account"), the following will apply:
    
    (a) User Account. To access certain features, Content and/or User Content available through the Mobile Application, we may require that you sign up using your username, email address and a password to create a User Account and profile about you, your writing, and your skills (a "Profile"). If you do not create a User Account and Profile, you may not have access to certain functionality of the Mobile Application. We use reasonable precautions to protect the privacy of your username, password, and User Account information. You, however, are ultimately responsible for protecting your username, password, and User Account information from disclosure to third parties, and you are not permitted to circumvent the use of required encryption technologies, if any. You agree to: (i) immediately notify us of any unauthorized use of your username, password, or User Account, or any other breach of security; (ii) ensure that you exit from your User Account at the end of each session; and (iii) use a security passcode to secure your device where your User Account information is stored. While we may provide certain encryption technologies and use other reasonable precautions to protect your confidential information and provide suitable security, we do not and cannot guarantee or warrant that information transmitted through the Internet is secure, or that such transmissions are free from delay, interruption, interception or error.
    
    (b) Accurate Information. In creating and using your User Account and Profile, you agree to: (i) provide true, accurate, current, and complete information about yourself on any registration form required for the Mobile Application, including, but not limited to, your email address (such information being the "Registration Data"); and (ii) maintain and promptly update the Registration Data to keep it true, accurate, current, and complete. If you provide any information that is untrue, inaccurate, not current, or incomplete, or if we have reasonable grounds to suspect that such information is untrue, inaccurate, not current, or incomplete, then we have the right to suspend or terminate your User Account and refuse any and all current or future use of your User Account.
    
    (c) Non-Transferability of User Account. Each User is only permitted to have one User Account. User Accounts and usernames are non-transferable, and all Users are obligated to take preventative measures to prohibit unauthorized Users from accessing the Mobile Application with his or her username and password. You agree that you are solely responsible for activity that occurs under your User Account. We are entitled to act on all instructions received by anyone using your User Account, and we reserve the right to pursue any and all claims against any User of your User Account.
    
    (d) Account Deactivation. We reserve the right to deactivate or cancel a User Account in our sole discretion, including for the following reasons: (i) you request such deactivation; (ii) you are deceased; (iii) you do not respond to repeated communication attempts regarding the status of your User Account; (iv) you fail to make payments related to your User Account (if applicable); (v) you reside in or relocate to a country where use of a User Account is prohibited under applicable law; (vi) you act in a fraudulent or an inappropriate manner while using the User Account; or (vii) after two (2) years of inactivity.
    
    4.6 Objectionable Material. You acknowledge that, in using the Mobile Application and accessing the Content and/or the User Content, you may encounter material that you deem to be disturbing, offensive or objectionable. You agree to use the Mobile Application at your sole risk and that we will have no liability to you for material that may be disturbing, objectionable or offensive to you.
    
    4.7 Not Intended for Children and Other Age Requirements. The Mobile Application are not intended or designed to attract children under the age of thirteen (13). You affirm that you are more than eighteen (18) years of age, or are an emancipated minor, and are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations, and warranties set forth in these Terms, and to abide by and comply with these Terms.
    
    4.8 DISCLAIMERS.
    
    (a) No Warranties for Mobile Application. When using the Mobile Application, information will be transmitted in such a way that may be beyond our control. Accordingly, we make no warranty concerning the delay, failure, interruption, or corruption of any data, the Content, the User Content or any other information transmitted in connection with the use of the Mobile Application. YOU EXPRESSLY AGREE THAT YOUR USE OF THE MOBILE APPLICATION IS AT YOUR SOLE RISK. THE MOBILE APPLICATION, THE CONTENT, AND THE USER CONTENT ARE PROVIDED "AS IS" AND "AS AVAILABLE" FOR YOUR USE, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, UNLESS THESE WARRANTIES ARE LEGALLY INCAPABLE OF EXCLUSION. WE MAKE NO REPRESENTATIONS OR WARRANTIES THAT THE MOBILE APPLICATION, THE CONTENT, THE USER CONTENT, OR ANY SERVICES OR FEATURES OFFERED IN CONNECTION WITH THE MOBILE APPLICATION ARE OR WILL REMAIN UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE WEB PAGES ACCESSIBLE ON OR THROUGH THE MOBILE APPLICATION, OR THE SERVERS USED IN CONNECTION WITH THE MOBILE APPLICATION, ARE OR WILL REMAIN FREE FROM ANY VIRUSES, WORMS, TIME BOMBS, DROP DEAD DEVICES, TROJAN HORSES, OR OTHER HARMFUL COMPONENTS. WE DO NOT GUARANTEE THAT YOU WILL BE ABLE TO ACCESS OR USE THE MOBILE APPLICATION AT TIMES OR LOCATIONS OF YOUR CHOOSING, OR THAT WE WILL HAVE ADEQUATE CAPACITY FOR THE MOBILE APPLICATION AS A WHOLE OR IN ANY SPECIFIC GEOGRAPHIC AREA. WE MAKE NO REPRESENTATION OR WARRANTY REGARDING GOVERNMENT COMPLIANCE OF ANY SOFTWARE USED IN RUNNING THE MOBILE APPLICATION.
    
    (b) Plagiarism. No part of another User's work may be used or reproduced by you in any manner whatsoever without express written permission of the author(s). GetItWrite disclaims all liability associated with plagiarism committed by any Users of the Mobile Application.
    
    (c) Indemnification. You agree to defend, indemnify, and hold harmless GetItWrite and our directors, officers, employees, agents, successors and assigns from and against any and all claims, demands, suits, proceedings, liabilities, judgments, losses, damages, expenses, and costs (including, but not limited to, reasonable attorneys' fees) assessed or incurred by us, directly or indirectly, with respect to or arising out of: (i) your failure to comply with these Terms; (ii) your breach of your obligations under these Terms; (iii) your use of the rights granted hereunder, including, but not limited to, any claims made by any third parties; and/or (iv) any claim that your User Content caused damage to or violated the rights of a third party.
    
    (d) Your Responsibilities. You are responsible for establishing such procedures as you deem appropriate to verify the accuracy of data that you transmit using the Mobile Application, and we will have no obligation to verify the accuracy of that data. While we reserve the right to review any and all User Content made available through the Mobile Application, you will remain responsible for your User Content. Your use of the Mobile Application is subject to the additional disclaimers and caveats that may appear throughout the Mobile Application. GetItWrite is not responsible for an individual's submissions, the quality of critiques and other actions of individual Users.
    
    (e) Network Access and Devices. You are responsible for obtaining the data network access necessary to use the Mobile Application. If you are accessing the Mobile Application on your mobile device, your network's data and messaging rates and fees may apply. You are responsible for acquiring and updating compatible hardware or devices necessary to access and use the Mobile Application and any updates thereto. We do not guarantee that the Mobile Application, or any portion thereof, will function on any particular hardware or devices. In addition, all Mobile Application may be subject to malfunctions and delays inherent in the use of the Internet and electronic communications.
    
    (f) No Professional Advice. All information and resources found on or accessible through the Mobile Application are based on the opinions of the author(s) unless otherwise noted. You acknowledge and agree that, by providing access to the Mobile Application, we are not rendering or providing any professional opinions on any of the matters discussed or included on the Mobile Application, and we will not be liable to anyone for any act or failure to act relating to any advice listed on or provided through the Mobile Application, whether that advice is included in the Content provided by us or the comments or discussions of other Users of the Mobile Application. We are not responsible for events arising from the distribution of any information that you choose to publicly post or share through the Mobile Application.
    
    4.11 Limitation of Liability. IN NO EVENT WILL WE OR OUR AFFILIATES, OR ANY OF OUR RESPECTIVE OFFICERS, DIRECTORS, AGENTS OR OTHER REPRESENTATIVES, BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, PUNITIVE, OR CONSEQUENTIAL DAMAGES OF ANY KIND ARISING FROM YOUR USE OF OR INABILITY TO USE THE MOBILE APPLICATION, THE CONTENT, AND/OR THE USER CONTENT PROVIDED IN CONNECTION WITH THE MOBILE APPLICATION, OR FOR ANY OTHER CLAIM RELATED IN ANY WAY TO YOUR USE OF THE MOBILE APPLICATION, THE CONTENT AND/OR ANY USER CONTENT PROVIDED ON OR THROUGH THE MOBILE APPLICATION. IN ADDITION, WE WILL NOT BE LIABLE FOR ANY NEGATIVE REPERCUSSIONS TO ANYONE BASED ON THE USE OF OR INABILITY TO USE THE MOBILE APPLICATION, INCLUDING, BUT NOT LIMITED TO, ANY LOST GOODWILL OR LOST PROFITS. WE ARE NOT LIABLE FOR ANY PERSONAL INJURY, INCLUDING DEATH, OR PROPERTY DAMAGE CAUSED BY YOUR USE OR MISUSE OF THE MOBILE APPLICATION AND/OR ANY CONTENT. WE ARE NOT RESPONSIBLE FOR (A) INACCURACIES OR ERRORS IN OR OMISSIONS FROM THE CONTENT; (B) DELAYS, ERRORS, OR INTERRUPTIONS IN THE TRANSMISSION OR DELIVERY OF THE CONTENT; OR (C) LOSS OR DAMAGE ARISING THEREFROM OR OCCASIONED THEREBY, OR BY ANY REASON OF NONPERFORMANCE. REMEDIES UNDER THESE TERMS ARE EXCLUSIVE AND ARE LIMITED TO THOSE EXPRESSLY PROVIDED FOR IN THESE TERMS. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, OUR ENTIRE LIABILITY SHALL BE LIMITED TO THE GREATER OF (i) THE AMOUNT THAT YOU PAID FOR THE SERVICES THAT YOU RECEIVED THROUGH THE MOBILE APPLICATION DURING THE TWELVE (12) MONTH PERIOD IMMEDIATELY BEFORE YOUR CLAIM AROSE, OR (ii) $1,000. BECAUSE SOME STATES AND JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, IN SUCH STATES OR JURISDICTIONS, OUR LIABILITY WILL BE LIMITED TO THE GREATEST EXTENT PERMITTED BY APPLICABLE LAW. THESE TERMS GIVE YOU SPECIFIC LEGAL RIGHTS. YOU MAY ALSO HAVE OTHER RIGHTS THAT MAY VARY FROM ONE STATE OR JURISDICTION TO ANOTHER.
    
    4.12 Third Party Content and Third Party Applications.
    
    (a) Generally. We may provide hyperlinks to other websites maintained by third parties, or we may provide third party content on the Mobile Application by framing or other methods (collectively, "Third Party Content"). In addition, the Mobile Application may include certain applications, features, programs and services provided by third parties (collectively, "Third Party Applications"). We do not monitor Third Party Content or Third Party Applications and can make no guarantee as to the accuracy or completeness of such Third Party Content or Third Party Applications. The links to third party websites, any Third Party Content, and any Third Party Applications are provided for your convenience and information only. The content on any linked website or in any Third Party Application is not under our control and we are not responsible for the content of linked websites and/or Third Party Applications, including any further links contained in a third party website. We make no representation or warranty in connection with any Third Party Content or Third Party Application, which at all times and in each instance is provided "as is." If you decide to access any of the third party websites linked to the Mobile Application, any Third Party Content, and/or any Third Party Application, you do so entirely at your own risk. If a third party links or refers to the Mobile Application, it is not necessarily an indication of an endorsement, authorization, sponsorship, affiliation, joint venture, or partnership by or with us. In most cases, we are not even aware that a third party has linked to or refers to the Mobile Application.
    
    (b) Affiliate Links. The Mobile Application may include links to one or more Third Party Applications or to Third Party Content that might entitle GetItWrite to be paid a fee if a User clicks on the link and purchases products or services. GetItWrite will endeavor to clearly mark those links as such when this is the case.
    
    4.13 Intellectual Property. The Content of the Mobile Application is intellectual property owned, controlled and/or licensed by us and/or our affiliates, or intellectual property that we are legally permitted to access and use. All applicable intellectual property laws, including copyright laws, protect our rights in and to the Content. No portion of the Content and/or User Content may be reproduced in any form or by any means, except as provided in Section 4.2 (Mobile Application Use and Content) and elsewhere in these Terms. We are the owner or authorized licensee of, or are otherwise permitted to use, all trademarks, service marks, and logos used and displayed by us on the Mobile Application. All trademarks and service marks of GetItWrite that may be referred to on the Mobile Application are the property of GetItWrite or one of our affiliates. Other parties' trademarks and service marks that may be referred to on the Mobile Application are the property of their respective owners. Nothing on the Mobile Application should be construed as granting, by implication, estoppel, or otherwise, any license or right to use any of our, or our affiliates', trademarks, service marks, logos, or copyrighted materials without our prior written permission.
    
    4.14 Copyright Complaints. We own, protect and enforce copyright and other rights in our own intellectual property, and respect the intellectual property rights of others. We will respond to allegations of copyright infringement. A copyright owner may file a takedown notice with an online service provider of an alleged copyright infringement. During this process, the service provider responds by taking down the alleged infringing content, and takes reasonable steps to contact the owner of the removed content so that a counter-notification may be filed, if appropriate. If a valid counter-notification is filed, we typically will restore the content in question, unless we receive notice from the notification provider that a legal action has been filed seeking a court order to restrain the alleged infringer from engaging in the infringing activity. We may provide copies of such notices to the affected parties or to any other third parties, at our discretion and as required by law. Our Privacy Policy does not apply to any information contained in these notices.
    
    When notifying us of potential infringement, you must include the following:
    •    identification of the copyrighted work(s) claimed to have been infringed. If multiple copyrighted works are involved, then a representative list of those works on the Mobile Application;
    •    identification of the allegedly infringing material that is to be removed;
    •    information reasonably sufficient to permit us to locate the allegedly infringing material on the Mobile Application;
    •    contact information reasonably sufficient to permit us to contact the complaining party, such as an address, telephone number, or email address;
    •    a statement that the complaining party has a good faith belief that use of the material is in fact infringing and not authorized by the copyright owner, its agent, or the law;
    •    a statement, made under penalty of perjury, that the information set forth in the notification is accurate and, where relevant, that the complaining party is authorized to act on behalf of the copyright owner; and
    •    the signature, physical or electronic, of the copyright owner or a person authorized to act on his or her behalf.
    A provider of content subject to a claim of infringement may make a counter-notification. To file a counter-notification with us, please provide a written communication containing the following:
    •    identification of the allegedly infringing material that was removed or disabled;
    •    a statement that, under penalty of perjury, you have a good faith belief that the material was removed or disabled as a result of mistake or misidentification of the material to be removed or disabled;
    •    your name, address, and telephone number, and a statement that you consent to the jurisdiction of the Federal District Court for the judicial district in which your postal address is located, and that you will accept service of process from the party who submitted the infringement notification or his, her, or its principal or agent; and
    •    the signature, physical or electronic, of you or a person authorized to act on your behalf.
    We will promptly provide the party that provided the notice of alleged infringement with a copy of the counter-notification, and inform the complaining party that we intend to restore the removed or disabled content. If we do not receive notice that a lawsuit has been filed after we provide notice of the counter-notification, we will restore the removed or disabled content. Until that time, your content will remain removed or disabled. Notice of alleged infringement must be sent by electronic mail at , or by certified mail and marked "Copyright Infringement" at Box 761 Sankt Göransgatan 67, 112 38, Stockholm - UK. Before filing notice of copyright infringement, you must make a careful determination as to whether or not the use of the material at issue is or may be protected by the "fair use" doctrine. You could potentially be held liable for costs and attorneys' fees should you file a takedown notice where there is no infringing use. If you are unsure whether there is infringement, it may be advisable to seek legal counsel.
    
    4.15 Termination of Service. We may suspend or terminate your right to access portions of the Mobile Application at any time, without notice, for conduct that we believe violates these Terms and/or is harmful to other Users of the Mobile Application, to us, to our partners, to the contributors, to the business of our Internet service provider, or to other information providers, or as we otherwise deem appropriate, in our sole discretion.
    
    4.16 Additional Remedies. You acknowledge that your conduct that is inconsistent with these Terms may cause us irreparable damage for which remedies other than monetary relief may be inadequate. In such instances, you agree that we may seek injunctive or other equitable relief to restrain such conduct without the necessity of proving actual harm or posting a bond.
    
    4.17 User Content Policy.
    
    (a) The Mobile Application may now or in the future permit you to upload or post to the Mobile Application or otherwise submit to GetItWrite various forms of content, such as statements, reviews, ratings, opinions, text, graphics, questions, suggestions, messages, comments, feedback, ideas, notes, drawings, articles, stories about you, or any other content of any kind whatsoever that you publish publicly, for example on our blog, or that you submit to us (collectively, "User Content"). For the avoidance of doubt, User Content does not include Authored Work. You retain all rights in and to your own Authored Works that you upload in order to share privately with individuals who will comment on and analyze your work. Authored Work should not be posted publicly, and it should only be shared with writing partners you have connected with to analyze and comment on your work.
    
    (b) You warrant to GetItWrite that you own all rights in your User Content or all third party holders of rights in your User Content have validly and irrevocably granted to you the right to grant the rights and licenses set forth above. We do not claim ownership in your User Content. However, by submitting any User Content in any form to GetItWrite, in addition to other provisions of these Terms, you automatically grant GetItWrite, its affiliates, successors and assigns, a perpetual, irrevocable, royalty-free, worldwide, non-exclusive, sublicensable and assignable right and license to use, copy, reproduce, modify, adapt, publish, edit, translate, create derivative works from, transmit, distribute, publicly display and publicly perform such User Content for the purpose of displaying and promoting such User Content on the Mobile Application owned or operated by us, without further notice to you, or consent from you, and without any requirement to pay anything to you or anyone else. For the avoidance of doubt, we will NOT use, copy, reproduce, modify, adapt, publish, edit, translate, create derivative works from, transmit, distribute, publicly display and publicly perform your Authored Work. Such Authored Work will only be displayed to and used by the Users you choose to analyze and comment on your work, and we will only access such Authored Work in order to enforce these Terms and to fulfill our obligations hereunder.
    
    (c) We reserve the right, in our sole discretion, to review and approve User Content before or after it is made available to other Users on the Mobile Application. Please remember that, even if we review your User Content, you will be solely responsible for your User Content and the consequences of posting or publishing it. We do not endorse any User Content or any opinion, recommendation, or advice expressed on or through the Mobile Application, and we expressly disclaim any and all liability in connection with User Content. You acknowledge that GetItWrite, our site moderators and our agents reserve the right, in our sole discretion, to refuse, move, and/or remove User Content available on or through the Mobile Application that, in our judgment, does not comply with these Terms and any other rules of User conduct applicable to our Mobile Application, or is otherwise harmful, objectionable, or inaccurate. We are not responsible for any failure or delay in removing such User Content. You represent and warrant that neither your User Content nor your uploading, publishing or otherwise making available your User Content nor GetItWrite's use of your User Content as permitted herein will infringe, misappropriate or violate a third party's intellectual property or proprietary rights, or rights of publicity or privacy, or result in the violation of any applicable law or regulation.
    
    4.18 Code of Conduct.
    
    (a) General Rules. In addition to the other requirements set forth herein, while using the Mobile Application, you agree to abide by the following general rules:
    •    Any material you submit must be your own, or you must be authorized to submit such material.
    •    You are limited to one User Account per User.
    •    Critique reciprocation is required. If another User critiques/provides feedback on your Authored Work, reciprocation is expected, unless said User refuses. GetItWrite reserves the right to suspend or terminate Users who systematically do not return critiques to Users who critiqued their work.
    •    When providing feedback to another User, please give specific, actionable feedback. You are encouraged to highlight problematic areas and recommend ways for improvement. Please remember to do so without trying to alter another User's voice.
    •    Be polite. While the ultimate goal is to give constructive feedback, when done in writing, your tone can be misinterpreted. Please make a conscious effort to come across as encouraging while pointing out areas of improvement.
    •    Please respect people's opinions. Hearing that your hard work may be flawed can be discouraging. You have the right to disagree with a critique you received, but please try to be polite when responding.
    •    If a writing partner's style and tone does not work for you, thank them for their time and part ways after you’ve critiqued their work.
    (b) Prohibited Activities. In addition to the other restrictions set forth herein, while using the Mobile Application, you agree that you will not engage in the following activities:
    •    Engaging in Prohibited External Communication, as described in Section 4.2(c).
    •    Sharing your critique partner's work with anyone, unless that partner has given you explicit written permission.
    •    Posting work that is not your own or plagiarizing other people's work.
    •    Using the Mobile Application to promote violence, degradation, subjugation, discrimination or hatred against individuals or groups based on race, color, ethnicity, national origin, age, gender, gender identity, gender expression, sexual orientation, disability, physical appearance, body size, or religion.
    •    Posting the same content repeatedly or spamming.
    •    Solicitation for any goods or services, other than those supported and facilitated by GetItWrite.
    •    Using the GetItWriteMobile Application for any unlawful activities or in violation of any laws, regulations, or contractual provisions, or to induce others to do or engage in the same.
    •    Providing User Content that is defamatory, libelous, hateful, violent, obscene, pornographic, invasive of another's privacy, infringing of another's intellectual property rights, unlawful, or otherwise offensive, as determined by GetItWritein its sole discretion.
    4.19 Governing Law; Jurisdiction and Venue. You agree that all matters relating to your access to, or use of, the Mobile Application will be governed by the UK law, without regard to any conflict of laws principles. You agree and hereby submit to the exclusive personal jurisdiction and venue of UK Courts with respect to such matters.
    
    4.20 Local Laws. We make no representation that any Content or materials on the Mobile Application are appropriate or available for use in jurisdictions that are outside UK. Access to the Mobile Application from jurisdictions where such access is illegal is prohibited. If you choose to access the Mobile Application from other jurisdictions, you do so at your own initiative and are responsible for compliance with applicable local laws.
    
    4.21 Export Restrictions. Any software and all underlying information and technology downloaded or viewed from any of the Mobile Application or in connection with the services (collectively, the "Software or Technical Data") by you may be subject to export or import regulations in other countries. You are solely responsible for complying with all trade regulations and laws, both foreign and domestic, in your use and viewing of the Mobile Application, the Content, the User Content, and any of our products or services, including, but not limited to, the Software or Technical Data. Except as authorized by law, you agree and warrant not to export or re-export the Software or Technical Data to any country, or to any person, entity, or end-user subject to export controls.
    
    4.22 Comments. By submitting comments, information or feedback (collectively, "Feedback") to us via the phone, through email and/or the Mobile Application, you agree that the information submitted will be subject to our Privacy Policy. We may use Feedback in any manner that we may choose, including, but not limited to, the incorporation of suggested changes into our services and products, without notice or compensation to you.
    
    4.22 Reporting Conent. Several pieces of content on the app can be reported, including:
        •    Critiques
        •    Messages
        •    Comments
        •    Proposals
        •    Projects
    We will decide the appropriate action accordingly. If your content is reported we can delete your account without informing you, at any given moment.
    
    Your Consent To These Terms of Service
    By accessing and using the Mobile Application, you consent to and agree to be bound by these Terms. If we decide to change these Terms or some part of them, we will make an effort to post those changes on the page in the settings menu so that you will always be able to understand and agree to the terms and conditions governing your use of the Mobile Application. Your use of the Mobile Application following your acceptance of any amendment of these Terms will signify your assent to and acceptance of the revised Terms for all previously collected information and information collected from you in the future. If you have additional questions or comments of any kind, or if you see anything on the Mobile Application that you think is inappropriate, please let us know by sending your comments or requests to: getitwriteapp@gmail.com
    
    """).padding().navigationTitle("Terms and Conditions")
            }
        }
    }
}

struct AboutView: View {
    var body: some View {
        Text("Hello! Thanks for being here :) This app is made by a writer (currently querying) for others writers so we can meet, share and hopefully improve together. We're all new here so if the app is pretty empty, lets kick of this community and support each other!")
    }
}
